import React, { useState, useEffect } from 'react';
import { FarmerProfile, SmartAlert, ActivityLog } from '../types';
import { Page } from '../App';
import { getSmartAlerts } from '../services/geminiService';
import { LeafIcon, ArrowLeftIcon, BellIcon } from '../components/icons/Icons';


interface AlertsPageProps {
  profile: FarmerProfile;
  onNavigate: (page: Page) => void;
}

const PriorityIndicator: React.FC<{ priority: SmartAlert['priority'], large?: boolean }> = ({ priority, large=false }) => {
  const styles = {
    High: { bg: 'bg-red-100 dark:bg-red-900/50', text: 'text-red-800 dark:text-red-300', border: 'border-red-500' },
    Medium: { bg: 'bg-yellow-100 dark:bg-yellow-900/50', text: 'text-yellow-800 dark:text-yellow-300', border: 'border-yellow-500' },
    Low: { bg: 'bg-blue-100 dark:bg-blue-900/50', text: 'text-blue-800 dark:text-blue-300', border: 'border-blue-500' },
  };
  const style = styles[priority];
  if(large) {
      return <div className={`px-3 py-1 text-sm font-bold rounded-full ${style.bg} ${style.text}`}>{priority}</div>
  }
  return <span className={`w-3 h-3 rounded-full ${style.bg}`}></span>;
};


const AlertsPage: React.FC<AlertsPageProps> = ({ profile, onNavigate }) => {
  const [alerts, setAlerts] = useState<SmartAlert[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchAlerts = async () => {
      try {
        setLoading(true);
        setError(null);
        const activityLogs: ActivityLog[] = JSON.parse(localStorage.getItem('activityLogs') || '[]');
        const alertsString = await getSmartAlerts(profile, activityLogs);
        const alertsData = JSON.parse(alertsString);

        if (alertsData.error) {
          setError(alertsData.error);
        } else {
          const sortedAlerts = alertsData.sort((a: SmartAlert, b: SmartAlert) => {
            const priorityOrder = { High: 3, Medium: 2, Low: 1 };
            return priorityOrder[b.priority] - priorityOrder[a.priority];
          });
          setAlerts(sortedAlerts);
        }
      } catch (e) {
        setError('Failed to parse alert data.');
        console.error(e);
      } finally {
        setLoading(false);
      }
    };
    fetchAlerts();
  }, [profile]);


  return (
    <div className="flex flex-col h-screen max-h-screen font-sans">
      <header className="bg-white dark:bg-gray-800 shadow-md p-4 flex justify-between items-center z-10 border-b border-gray-200 dark:border-gray-700">
        <div className="flex items-center space-x-3">
          <LeafIcon className="h-8 w-8 text-green-600 dark:text-green-400" />
          <h1 className="text-2xl font-bold text-gray-800 dark:text-white">
            Krishi Mitra AI
          </h1>
        </div>
        <button
            onClick={() => onNavigate('dashboard')}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-200 bg-gray-100 dark:bg-gray-700 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
        >
            <ArrowLeftIcon className="h-5 w-5"/>
            Back to Dashboard
        </button>
      </header>
      
      <main className="flex-1 flex flex-col p-6 bg-gray-50 dark:bg-gray-800/50 overflow-y-auto">
        <div className="mb-6">
            <h2 className="text-3xl font-bold text-gray-800 dark:text-white flex items-center gap-3">
                <BellIcon className="h-8 w-8 text-orange-500" />
                <span>Smart Alerts & Reminders</span>
            </h2>
            <p className="text-gray-600 dark:text-gray-400">
                Proactive advice and timely reminders generated by AI.
            </p>
        </div>
        
        <div className="flex-1 space-y-4">
            {loading && <p className="text-center text-gray-600 dark:text-gray-300">Generating latest alerts...</p>}
            {error && <p className="text-center text-red-500 p-4 bg-red-100 dark:bg-red-900/50 rounded-lg">{error}</p>}
            
            {!loading && !error && alerts.length === 0 && (
                <div className="text-center p-8 bg-white dark:bg-gray-700 rounded-lg">
                    <p className="font-semibold text-lg">All Clear!</p>
                    <p className="text-gray-500 dark:text-gray-400">No new alerts or reminders for you at the moment.</p>
                </div>
            )}

            {alerts.map(alert => {
                 const style = {
                    High: { border: 'border-red-500' },
                    Medium: { border: 'border-yellow-500' },
                    Low: { border: 'border-blue-500' },
                  }[alert.priority];
                return (
                    <div key={alert.id} className={`p-4 bg-white dark:bg-gray-700 rounded-lg shadow-md border-l-4 ${style.border}`}>
                        <div className="flex justify-between items-start">
                            <h3 className="text-lg font-bold text-gray-800 dark:text-white">{alert.title}</h3>
                            <PriorityIndicator priority={alert.priority} large />
                        </div>
                        <p className="text-sm text-gray-600 dark:text-gray-300 mt-1">{alert.message}</p>
                        <p className="text-xs text-gray-400 dark:text-gray-500 mt-3 text-right">
                            Generated: {new Date(alert.timestamp).toLocaleString()}
                        </p>
                    </div>
                );
            })}
        </div>
      </main>
    </div>
  );
};

export default AlertsPage;
